# ---------------------------------------------------------------
# Menu config
# ---------------------------------------------------------------

# Header navigation menu.
# Value before `||` delimiter is the target link.
# Value after `||` delimiter is the name of FontAwesome icon.
# See: https://fontawesome.com/v4.7.0/icons/
# If not set, "question-circle-o" icon will be shown.
menu:
  home: / || home
  archives: /archives/ || folder-open
  categories: /categories/ || th
  tags: /tags/ || tags
  about: /about/ || user
  # reading: /reading/ || book
  # sitemap: /sitemap.xml || sitemap
  # You can also add a item by yourself.
  # xxx: /xxx/ || xxx

menu_settings:
  # Only show by icon.
  icon_only: false
  # Only show by text.
  text_only: false

# ---------------------------------------------------------------
# Site config
# ---------------------------------------------------------------

favicon:
  small: /images/favicon-16x16-stun.png
  medium: /images/favicon-32x32-stun.png
  # apple_touch_icon: /images/apple-touch-icon-stun.png
  # safari_pinned_tab: /images/logo-stun.svg

header:
  # Header height (Support for all types of CSS size units).
  height: 80%
  # Header navigation bar height (Support for all types of CSS size units).
  nav_height: 50px
  # Background image in the header.
  bg_image:
    enable: true
    # In theme directory (source/images): /images/avatar.png
    # In site directory (source/uploads): /uploads/avatar.png
    # You can also use a link of image.
    url: 
  # Blur filter effect of the header background.
  blur_effect:
    enable: false
    # Degree of blur.
    level: 15px

# Creative Commons 4.0 International License.
creative_commons:
  enable: true
  # Available: BY | BY-SA | BY-ND | BY-NC | BY-NC-SA | BY-NC-ND
  # For details, please see: https://creativecommons.org/share-your-work/licensing-types-examples
  license: BY-NC-SA
  # Show the CC license in the sidebar.
  sidebar: true
  # Show the CC license at the post bottom.
  post: true
  # You can set a language value if you prefer a translated version of CC license.
  # Valid values of language: en, zh, etc.
  # If not set, "en" will be used by default.
  language: en

# Back to top button.
back2top:
  enable: true
  icon:
    # Icon name in FontAwesome, see: https://fontawesome.com/v4.7.0/icons/
    # `rocket` is recommended.
    name: rocket
    # Animation of rocket launch.
    animation: true
    # Rotation Angle of icon.
    rotate: -45deg
    # Please use quote to wrap value (All CSS size units are supported).
    color: "#49b1f5"
    # Colour when the mouse hovers it.
    hover_color: "#fc6423"

# Footer of your site.
footer:
  # Background image in the footer.
  bg_image:
    enable: true
    # In theme directory (source/images): /images/avatar.png
    # In site directory (source/uploads): /uploads/avatar.png
    # You can also use a link of image.
    url: 
  # Copyright information.
  copyright:
    enable: true
    # If not set, will be used `author` from Hexo main config.
    #   (e.g. liuyib. All Rights Reserved.)
    text: 
    # Start time. If not set, the current year will be used.
    since: 
    # End time. If not set, the current year will be used.
    end: 
  # The icon between the copyright year and the owner.
  icon:
    enable: true
    # Icon name in FontAwesome, see: https://fontawesome.com/v4.7.0/icons/
    # `heart` is recommended with animation in red (#ff0000).
    name: heart
    # Heart beat animation.
    animation: true
    # Please use quote to wrap value (All CSS size units are supported).
    color: "#ff0000"
  # Hexo link (Powered by Hexo).
  powered:
    enable: true
    # Version info of Hexo after Hexo link (e.g. vX.X.X).
    version: true
  # Theme info link (Theme - stun).
  theme:
    enable: true
    # Version info of theme after theme info (e.g. vX.X.X).
    version: true
  # Beian icp information for Chinese users. see: http://www.miitbeian.gov.cn
  beian:
    enable: false
    # 备案 XXXXXXXX 号
    icp: 
  # Any custom text (e.g. Hosted by <a href="https://pages.github.com/" rel="noopener" target="_blank">Github Pages</a>).
  custom:
    enable: false
    text: 

# ---------------------------------------------------------------
# Sidebar config
# ---------------------------------------------------------------

sidebar:
  enable: true
  # Sidebar position, available values: left | right
  position: right
  # Sidebar offset from top menubar (Only px units are supported).
  offsetTop: 20px
  # Define the sidebar width, 260px ~ 360px is better (All CSS size units are supported).
  width: 300px
  # Horizon line.
  horizon_line: true

author:
  enable: true
  # Avatar in the sidebar.
  avatar:
    # In theme directory (source/images): /images/avatar.png
    # In site directory (source/uploads): /uploads/avatar.png
    # You can also use a link of image.
    url: /images/avatar.png
    # If true, the avatar would be displayed in a circle.
    rounded: true
    # The value should be chosen from 0 to 1.
    opacity: 1
    # Mouse hover animation, available value: turn | shake
    animation: turn
  # Your favorite motto (e.g. Talk is cheap, show me your code).
  motto: 

# Social links.
# Value before `||` delimiter is the target link.
# Value after `||` delimiter is the name of FontAwesome icon.
# See: https://fontawesome.com/v4.7.0/icons/
# If you can`t find a suitable icon, you can choose to display the original
#   text by adding the "origin" prefix (e.g. origin:sf, then "sf" will be show).
social:
  github: https://github.com/ || github
  google: https://plus.google.com/ || google
  twitter: https://twitter.com/ || twitter
  youtube: https://youtube.com/ || youtube
  segmentfault: https://segmentfault.com/ || origin:sf
  zhihu: https://www.zhihu.com/ || origin:知
  weibo: https://weibo.com/ || weibo
  wechat: yournumber || weixin
  telegram: yournumber || telegram
  qq: yournumber || qq
  # You can also add a link by yourself.
  # xxx: xxx || (origin:)xxx

social_setting:
  enable: false
  # Only show by icon.
  icon_only: true
  # Available values are equal to "justify-content" attribute in CSS.
  # e.g. flex-start | center | flex-end | space-between, etc.
  # For details, please see: https://developer.mozilla.org/zh-CN/docs/Web/CSS/justify-content
  text_align: center

# Table Of Contents in the Sidebar.
toc:
  enable: true
  # Automatically add list number to toc.
  number: true
  # If true, all words will be placed on the next lines when they overflow..
  wrap: true
  # If true, the toc of post will always be displayed, rather than the activated part of it.
  expand_all: false
  # Maximum heading depth of generated toc. You can set it in the
  #   post through `toc_max_depth` in Front-matter.
  # e.g. value: 3, will use h1~3 to generated toc.
  max_depth: 6

# Subscribe of email and rss.
feed:
  enable: false
  # Enter your email subscription link (e.g. http://eepurl.com/guAE6j).
  email: 
  # Enter the rss address of you set (e.g. /atom.xml)
  rss: 

# The reading progress of post.
reading_progress:
  enable: true
  # Please use the quote to wrap value (All CSS size units are supported).
  color: "#fc6423"
  # Support for all types of CSS size units.
  height: 1px

# ---------------------------------------------------------------
# Post config
# ---------------------------------------------------------------

# The meta-information at the front of the post.
post_meta:
  # Only show by icon.
  icon_only: false
  # Show create information.
  created:
    enable: true
    # Icon name in FontAwesome, see: https://fontawesome.com/v4.7.0/icons/
    icon: calendar-o
  # Show update information.
  updated:
    enable: true
    # Icon name in FontAwesome, see: https://fontawesome.com/v4.7.0/icons/
    icon: calendar-check-o
  # Count the reading time of the post.
  # Don't enable this before install dependencies
  #   by `npm install hexo-wordcount --save` in hexo directory
  #   and you must restart your hexo server.
  reading_time:
    enable: false
    # Icon name in FontAwesome, see: https://fontawesome.com/v4.7.0/icons/
    icon: clock-o
    # Set reading speed to estimate reading time.
    speed:
      # Reading speed of zh-CN.
      zh: 200
      # Reading speed of en-US.
      en: 80
  # Count the words of the post.
  # Don't enable this before install dependencies
  #   by `npm install hexo-wordcount --save` in hexo directory
  #   and you must restart your hexo server.
  word_count:
    enable: false
    # Icon name in FontAwesome, see: https://fontawesome.com/v4.7.0/icons/
    icon: file-word-o

# The article list on the homepage or archives page.
post_list:
  # Whether to paginate.
  paginate:
    home: true
    archives: false
  # Whether to show the top image of post.
  top_image:
    home: true

# The widget of post.
post_widget:
  # Show tags at the bottom of the post.
  tags: true
  # Show "post end" at the bottom of the post.
  end_text:
    enable: true
    # Show the horizon line before the text of the end.
    horizon_line: true

# Automatically retain article excerpt.
auto_excerpt:
  enable: false
  length: 150

# Stick post to the top.
# To enable this feature, you need to install dependencies `hexo-generator-index-pin-top`
# For details, see: https://github.com/netcan/hexo-generator-index-pin-top
stick_top:
  # Position of icon, available values: left | right
  position: right
  # Icon name in FontAwesome, see: https://fontawesome.com/v4.7.0/icons/
  icon: thumb-tack
  # Rotation Angle of icon.
  rotate: 45deg
  # Please use the quote to wrap value (All CSS size units are supported).
  color: "#999"

# Code highlight.
# values:
# - light
# - dark
# - ocean
highlight_theme: light

# Code wrap.
# values: true or false
code_word_wrap: true

# Horizonal alignment of img.
# values:
# - left
# - center
# - right
# 
# If you don't want to set the align of the image, please empty it,
#   then it will show by default.
img_horizonal_align: 

# Vertical alignment of text and images.
# values:
# - top
# - middle
# - bottom
text_vertical_align_with_img: bottom

# Reward
reward:
  enable: false
  alipay: 
  wechat: 

# ---------------------------------------------------------------
# Comment config
# ---------------------------------------------------------------

# Gitment
# See: https://github.com/imsun/gitment
gitment:
  enable: false
  # Github username.
  owner: 
  # Github repository.
  repo: 
  # Github Application Client ID
  client_id: 
  # Github Application Client Secret
  client_secret: 
  # Enable / Disable Lazy load. Enable is recommended.
  lazy: true

# Gittalk
# See: https://github.com/gitalk/gitalk
gitalk:
  enable: false
  # Github username.
  owner: 
  # Github repository.
  repo: 
  # Github Application Client ID
  client_id: 
  # Github Application Client Secret
  client_secret: 
  # GitHub repo owner and collaborators, only these guys can initialize github issues
  admin: 
  # Facebook-like distraction free mode
  distraction_free_mode: false
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language,
  #   you can set a force language value
  # Available values: en, zh-CN, es-ES, fr, ru, zh-TW
  language: 

# Livere
# See: https://www.livere.com/
livere:
  enable: false
  uid: 

# Disqus
# See: https://disqus.com/
disqus:
  enable: false
  shortname: 
  count: true

# ---------------------------------------------------------------
# Statistics and Analytics config
# ---------------------------------------------------------------

busuanzi:
  enable: true
  site:
    # Only show by icon.
    icon_only: false
    # Number of unique visitor to the entire site.
    uv:
      enable: true
      # Icon name in FontAwesome, see: https://fontawesome.com/v4.7.0/icons/
      icon: user
    # Number of page view to the entire site.
    pv:
      enable: true
      # Icon name in FontAwesome, see: https://fontawesome.com/v4.7.0/icons/
      icon: eye
  # Number of page view to a post.
  post_pv:
    # Only show by icon.
    icon_only: false
    enable: true
    # Icon name in FontAwesome, see: https://fontawesome.com/v4.7.0/icons/
    icon: eye

# ---------------------------------------------------------------
# Search config
# ---------------------------------------------------------------

# Algolia Search
# Dependencies: https://github.com/algolia/instantsearch.js/
algolia_search:
  enable: true
  hits:
    # Number of search results displayed per page.
    per_page: 10
  labels:
    # Whether to show stats of search.
    show_stats: true

# ---------------------------------------------------------------
# Other config
# ---------------------------------------------------------------

# Tag cloud.
# If not used, comment it or ignore it.
tag_cloud:
  # Color for tag (please use the quote to wrap value, only support HEX).
  start_color: "#a4d8fa"
  end_color: "#49b1f5"
  # Size for tag.
  min_size: 24
  max_size: 34
  # Maximum number of tags displayed. Change it if you have more than 200 tags.
  max_amount: 200

# Assets.
# In theme directory (source/css).
css: css
# In theme directory (source/js).
js: js
# In theme directory (source/images).
images: images

# CND for third libs.
cdn:
  css:
    fontawesome: https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css
  js:
    jquery: https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js
    velocity: https://cdn.jsdelivr.net/npm/velocity-animate@latest/velocity.min.js
    velocity-ui: https://cdn.jsdelivr.net/npm/velocity-ui-pack@latest/velocity.ui.min.js
