# ==================================================
# Basic config
# ==================================================

# Header menu navigation
menu:
  home: /
  archives: /archives
  categories: /categories
  tags: /tags
  about: /about
  # XXX: /xxx

# Favicon
favicon: /imgs/favicon.ico

# Avatar in the sidebar
avatar: /imgs/my_avatar.jpg

# Social links
social:
  github:
  segmentfault:
  twitter:
  weibo:
  wechat:
  qq:
  telegram:

# Subscribe of email and rss
feed:
  mail:
  rss:

# Stylesheets loaded in the <head>
stylesheets:
  - /css/index.css

# Scripts loaded in the end of the body
scripts:
  - /js/utils.js
  - /js/scroll.js
  - /js/sidebar.js
  - /js/post.js

# CND for libs
cdn:
  # css:
  js:
    jquery: https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js
    velocity: https://cdn.jsdelivr.net/npm/velocity-animate@latest/velocity.min.js

# ==================================================
# Advanced config
# ==================================================

# --------------------------------------------------
# Tag cloud
# If not used, comment it or ignore it
# --------------------------------------------------
tag:
  # Color for tag（please use quote to wrap value, only support HEX）
  start_color: '#a4d8fa'
  end_color: '#49b1f5'
  # Font size for tag
  min_font_size: 16
  max_font_size: 30

# --------------------------------------------------
# Code highlight
# values:
# - light
# - dark
# - ocean
# --------------------------------------------------
highlight_theme: light

# --------------------------------------------------
# Reward
# --------------------------------------------------
reward:
  enable: true
  qr_img_url:
    alipay:
    wechat:

# --------------------------------------------------
# Icon
# --------------------------------------------------
# Whether to show header menu icon
# values: true or false
header_menu_icon_show: true

# --------------------------------------------------
# Whether to wrap lines when code is overflow
# values: true or false
# --------------------------------------------------
code_word_wrap: true

# --------------------------------------------------
# Horizonal alignment of img
# values:
# - left
# - center
# - right
# 
# If you don't want to set the align of img, please empty it
# --------------------------------------------------
img_horizonal_align: 

# --------------------------------------------------
# Vertical alignment of text and images
# values:
# - top
# - middle
# - bottom
# --------------------------------------------------
text_vertical_align_with_img: bottom

# --------------------------------------------------
# Comments
# --------------------------------------------------


# --------------------------------------------------
# Copyright
# --------------------------------------------------
# Copyright of articles
post_copyright:
  enable: true
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# Copyright at the bottom of the site
site_copyright:
  enable: true
  start: 2019
  # If not set, default is the latest year
  end:

# --------------------------------------------------
# ICP
# --------------------------------------------------
ICP:
  enable: false
  text:

# --------------------------------------------------
# PWA
# See https://github.com/JLHwung/hexo-offline
# --------------------------------------------------
pwa:
  enable: true
  manifest: /manifest.json

# --------------------------------------------------
# Busuanzi count for PV / UV in site
# --------------------------------------------------
busuanzi:
  # Count values only if the other configs are false
  enable: true
  # Custom uv span for the whole site
  site_uv: true
  site_uv_header: <i class="fa fa-user"></i>
  site_uv_footer:
  # Custom pv span for the whole site
  site_pv: true
  site_pv_header: <i class="fa fa-eye"></i>
  site_pv_footer:
  # Custom pv span for one page only
  page_pv: true
  page_pv_header: <i class="fa fa-file"></i>
  page_pv_footer:

# --------------------------------------------------
# Canvas ribbon
# See: https://github.com/hustcc/ribbon.js
# --------------------------------------------------
canvas_ribbon:
  enable: false
  size: 150
  alpha: 0.6
  zIndex: -1
  click_to_change: false
