# ---------------------------------------------------------------
# Site Information config
# ---------------------------------------------------------------

favicon:
  small: /imgs/favicon-16x16-stun.png
  medium: /imgs/favicon-32x32-stun.png
  # apple_touch_icon: /imgs/apple-touch-icon-stun.png
  # safari_pinned_tab: /imgs/logo-stun.svg

header:
  # Header height (Only percentage units are supported).
  height: 80%
  # Header navigation bar height (Support for all types of CSS size units).
  nav_height: 50px
  # Background image in the header.
  bg_image:
    enable: true
    # In theme directory (source/imgs): /images/avatar.png
    # In site directory (source/uploads): /uploads/avatar.png
    # You can also use a link of image.
    url: 
  # Blur filter effect of the header background.
  blur_effect:
    enable: false
    # Degree of blur.
    level: 15px

# Creative Commons 4.0 International License.
creative_commons:
  enable: true
  # Available: BY | BY-SA | BY-ND | BY-NC | BY-NC-SA | BY-NC-ND
  # For details, please see: https://creativecommons.org/share-your-work/licensing-types-examples
  license: BY-NC-SA
  # Show the CC license in the sidebar.
  sidebar: true
  # Show the CC license at the post bottom.
  post: true
  # You can set a language value if you prefer a translated version of CC license.
  # Valid values of language: en, zh, etc.
  # If not set, "en" will be used by default.
  language: en

# Back to top button.
back2top:
  enable: true
  icon:
    # Icon name in FontAwesome, see: https://fontawesome.com/icons?d=listing
    # `rocket` is recommended.
    name: rocket
    # Animation of rocket launch.
    animation: true
    # Rotation Angle of icon.
    rotate: -45deg
    # Please use quote to wrap value (Support for all types of CSS color units).
    color: "#49b1f5"
    # Colour when the mouse hovers it.
    hover_color: "#fc6423"

# Footer of your site.
footer:
  # Background image in the footer.
  bg_image:
    enable: true
    # In theme directory (source/imgs): /images/avatar.png
    # In site directory (source/uploads): /uploads/avatar.png
    # You can also use a link of image.
    url: 
  # Copyright information.
  copyright:
    enable: true
    # If not set, will be used `author` from Hexo main config.
    text: 
    # Specify the date when the site was setup. If not set, the current year will be used.
    since: 
    # Specify the date when the site ended. If not set, the current year will be used.
    end: 
  # Icon between the copyright year and the owner.
  icon:
    enable: true
    # Icon name in FontAwesome, see: https://fontawesome.com/icons?d=listing
    # `heart` is recommended with animation in red (#ff0000).
    name: heart
    # Heart beat animation.
    animation: true
    # Please use quote to wrap value (Support for all types of CSS color units).
    color: "#ff0000"
  # Hexo link (Powered by Hexo).
  powered:
    enable: true
    # Version info of Hexo after Hexo link (e.g. vX.X.X).
    version: true
  # Theme info link (Theme - stun).
  theme:
    enable: true
    # Version info of theme after theme info (e.g. vX.X.X).
    version: true
  # Beian icp information for Chinese users. see: http://www.miitbeian.gov.cn
  beian:
    enable: false
    # 备案 XXXXXXXX 号
    icp: 
  # Any custom text (e.g. Hosted by <a href="https://pages.github.com/" rel="noopener" target="_blank">Github Pages</a>).
  custom:
    enable: false
    text: 

# ---------------------------------------------------------------
# Menu config
# ---------------------------------------------------------------

# Header navigation menu.
# Value before `||` delimiter is the target link.
# Value after `||` delimiter is the name of FontAwesome icon. If not set, "question-circle-o" icon will be shown.
menu:
  home: / || home
  archives: /archives/ || folder-open
  categories: /categories/ || th
  tags: /tags/ || tags
  about: /about/ || user
  # reading: /reading/ || book
  # sitemap: /sitemap.xml || sitemap
  # xxx: /xxx/ || xxx

menu_settings:
  icon: true

# ---------------------------------------------------------------
# Sidebar config
# ---------------------------------------------------------------

sidebar:
  enable: true
  # Sidebar position, available values: left | right
  float: right
  # Sidebar offset from top menubar (Support for all types of CSS size units).
  offsetTop: 20px
  # Define the sidebar width, 260px ~ 360px is better (Support for all types of CSS size units).
  width: 300px
  # Horizon line.
  horizon_line: true

author:
  enable: true
  # Avatar in the sidebar.
  avatar:
    # In theme directory (source/imgs): /images/avatar.png
    # In site directory (source/uploads): /uploads/avatar.png
    # You can also use a link of image.
    url: 
    # If true, the avatar would be displayed in a circle.
    rounded: true
    # The value should be chosen from 0 to 1.
    opacity: 1
    # Mouse hover animation, available value: turn | shake
    animation: turn

  # Your favorite motto (e.g. Talk is cheap, show me your code).
  motto: Talk is cheap, show me your code.

# Social links.
# Value before `||` delimiter is the target link.
# Value after `||` delimiter is the name of FontAwesome icon.
# If you can`t find a suitable icon, you can choose to display the original.
#   text by adding the "origin" prefix (e.g. origin:sf, then "sf" will be show).
social:
  enable: true
  github: https://github.com/ || github
  google: https://plus.google.com/ || google
  twitter: https://twitter.com/ || twitter
  youtube: https://youtube.com/ || youtube
  segmentfault: https://segmentfault.com/ || origin:sf
  zhihu: https://www.zhihu.com/ || origin:知
  weibo: https://weibo.com/ || weibo
  wechat: yournumber || weixin
  telegram: yournumber || telegram
  qq: yournumber || qq

social_setting:
  # Only show social links by an icon.
  icon_only: true
  # Available values are equal to "justify-content" attribute in CSS.
  # e.g. flex-start | center | flex-end | space-between, etc.
  # For details, please see: https://developer.mozilla.org/zh-CN/docs/Web/CSS/justify-content
  text_align: center

# Table Of Contents in the Sidebar.
toc:
  enable: true
  # Automatically add list number to toc.
  number: true
  # If true, all words will be placed on next lines if header width longer then sidebar width.
  wrap: true
  # Maximum heading depth of generated toc. You can set it in one post through `toc_max_depth` in Front-matter.
  # e.g. value: 3, will use h1~3 to generated toc.
  max_depth: 5

# Subscribe of email and rss.
feed:
  enable: false
  # Enter your email subscription link (e.g. http://eepurl.com/guAE6j).
  email: 
  # rss: 

# The reading progress of post.
reading_progress:
  enable: true
  # Please use the quote to wrap value (Support for all types of CSS color units).
  color: "#fc6423"
  # Support for all types of CSS size units.
  height: 1px

# ---------------------------------------------------------------
# Post config
# ---------------------------------------------------------------

# The meta-information at the front of the post.
post_meta:
  icon_only: false
  # Show create information.
  created:
    enable: true
    # Icon name in FontAwesome, see: https://fontawesome.com/v4.7.0/icons/
    icon: calendar-o
  # Show update information.
  updated:
    enable: true
    # Icon name in FontAwesome, see: https://fontawesome.com/v4.7.0/icons/
    icon: calendar-check-o
  # Count the reading time of the post.
  # Don't enable it before you see: https://github.com/willin/hexo-wordcount
  reading_time:
    enable: false
    # Icon name in FontAwesome, see: https://fontawesome.com/v4.7.0/icons/
    icon: clock-o
    # Set reading speed to estimate reading time.
    speed:
      # Reading speed of zh-CN.
      zh: 200
      # Reading speed of en-US.
      en: 80
  # Count the words of the post.
  # Don't enable it before you see: https://github.com/willin/hexo-wordcount
  word_count:
    enable: false
    # Icon name in FontAwesome, see: https://fontawesome.com/v4.7.0/icons/
    icon: file-word-o

# Code highlight.
# values:
# - light
# - dark
# - ocean
highlight_theme: light

# Code wrap.
# values: true or false
code_word_wrap: true

# Horizonal alignment of img.
# values:
# - left
# - center
# - right
# 
# If you don't want to set the align of the image, please empty it, then it will show by default.
img_horizonal_align: 

# Vertical alignment of text and images.
# values:
# - top
# - middle
# - bottom
text_vertical_align_with_img: bottom

# Show tags at the bottom of the post.
post_tags: true

# Show "post end" at the bottom of the post.
post_end_text:
  enable: true
  # Show horizon line before the text that prompts the end of the article.
  horizon_line: true

# Reward
reward:
  enable: false
  alipay: 
  wechat: 

# ---------------------------------------------------------------
# Comment config
# ---------------------------------------------------------------

# Gitment
# See: https://github.com/imsun/gitment
gitment:
  enable: true
  # Github username.
  owner: 
  # Github repository.
  repo: 
  client_id: 
  client_secret: 
  # Enable / Disable Lazy load. Enable is recommended.
  lazy: true

# ---------------------------------------------------------------
# Statistics and Analytics config
# ---------------------------------------------------------------

busuanzi:
  enable: true
  # Number of unique visitor to the entire site.
  site_uv:
    enable: true
    # Icon name in FontAwesome, see: https://fontawesome.com/icons
    icon: user
  # Number of page view to the entire site.
  site_pv:
    enable: true
    # Icon name in FontAwesome, see: https://fontawesome.com/icons
    icon: eye
  # Number of page view to a post.
  post_pv:
    enable: true
    # Icon name in FontAwesome, see: https://fontawesome.com/icons
    icon: eye

# ---------------------------------------------------------------
# Other config
# ---------------------------------------------------------------

# Tag cloud.
# If not used, comment it or ignore it.
tag_cloud:
  # Color for tag (please use the quote to wrap value, only support HEX).
  start_color: "#a4d8fa"
  end_color: "#49b1f5"
  # Size for tag.
  min_size: 24
  max_size: 34
  # Maximum number of tags displayed. Change it if you have more than 200 tags
  max_amount: 200

# Assets.
# In theme directory (source/css).
css: css
# In theme directory (source/js).
js: js
# In theme directory (source/imgs).
img: imgs

# CND for third libs.
cdn:
  css:
    fontawesome: https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css
  js:
    jquery: https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js
    velocity: https://cdn.jsdelivr.net/npm/velocity-animate@latest/velocity.min.js

# Scripts loaded at the end of the body.
scripts:
  - /js/utils.js
  - /js/scroll.js
  - /js/header.js
  - /js/sidebar.js
  - /js/post.js
